config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root "pages#home"

  get "register" => "users#new", as: "register"
  get "login" => "sessions#new", as: "login"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy", as: "logout"

  resources :users, except: [:index] do
    resources :todos, except: [:show] do
      member do
        patch :toggle_completed
      end
    end
  end

  get "*path" => "pages#home"


  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord

  belongs_to :user

  validates :title, presence: true, length: { minimum: 3, maximum: 100 }
  
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  has_many :todos, dependent: :destroy


  validates :username, length: { minimum: 3, maximum: 25}, uniqueness: { case_sensitive: false }

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true

  validates :password, length: { minimum: 6, maximum: 25}, allow_nil: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_user
    current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def logged_in?
    !!current_user
  end

  helper_method :logged_in?

  def same_user?(user)
    current_user == user
  end

  helper_method :same_user?

  def require_logged_in
    unless logged_in?
      flash[:alert] = "You must be logged in to access this section"
      redirect_to login_url
    end
  end

  def require_same_user
    # fail
    if params[:user_id]
      user = User.find(params[:user_id])
    else
      user = User.find(params[:id])
    end
    unless same_user?(user)
      flash[:alert] = "You can only manage your own account"
      redirect_to user_path(current_user)
    end

  rescue ActiveRecord::RecordNotFound
    redirect_to root_url, status: :see_other

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "You have logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render :new, status: :unauthorized
    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, status: :see_other, notice: "You have logged out!"
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  before_action :require_logged_in
  before_action :require_same_user

  def index
    @todos = current_user.todos
    @uncompleted_todos_count = uncompleted_todos.count
  end

  def new
    @todo = Todo.new
    @user = current_user
  end

  def create
    @todo = Todo.new(todos_params)
    @todo.user = current_user
   
    if @todo.save
      flash[:notice] = "Todo was successfully created"
      redirect_to user_todos_path(current_user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @todo = Todo.find(params[:id])
    @user = current_user
  end

  def update
    @todo = Todo.find(params[:id])

    if @todo.update(todos_params)
      flash[:notice] = "Todo text was successfully updated"
      redirect_to user_todos_path(current_user)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def toggle_completed
    @todo = Todo.find(params[:id])
    if @todo.toggle!(:completed)
      flash[:notice] = "Todo completed status was successfully updated" 
      redirect_to user_todos_path(current_user)
    else
      flash.now[:alert] = "Todo completed status could not be updated"
      render :index, status: :unprocessable_entity
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    flash[:notice] = "Todo was successfully deleted"
    redirect_to user_todos_url(current_user), status: :see_other
  end

  private

  def todos_params
    params
      .require(:todo)
      .permit(:title)
  end

  def uncompleted_todos
    @todos.where(completed: false)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_logged_in, except: [:new, :create]
  before_action :require_same_user, except: [:new, :create]

  def show
    @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url, status: :see_other
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You have successsfully signed up!"
      redirect_to user_path(@user)
    else
      render :new, status: :unprocessable_entity
    end

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] = "You have successsfully updated your profile!"
      redirect_to user_path(@user)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    session[:user_id] = nil
    @user.destroy
    flash[:notice] = "You have successsfully deleted your account!"
    redirect_to root_url, status: :see_other
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div>
  <nav class="bg-blue-500 p-4">
    <ul class="flex justify-left text-white">
      <% if logged_in? %>
        <li class="ml-3">
          <%= link_to "Dashboard (#{ current_user.username })", user_path(current_user), class: "hover:text-gray-200" %>
        </li>
        <li class="ml-3">
          <%= link_to "Logout", logout_path, data: { turbo_method: :delete }, class: "hover:text-gray-200" %>
        </li>
      <% else %>
        <li class="ml-3">
          <%= link_to "Home", root_path, class: "hover:text-gray-200" %>
        </li>
        <li class="ml-3">
          <%= link_to "Register", register_path, class: "hover:text-gray-200" %>
        </li>
        <li class="ml-3">
          <%= link_to "Login", login_path, class: "hover:text-gray-200" %>
        </li>
      <% end %>
    </ul>
  </nav>
</div>

    <% flash.each do |message_type, message| %>
      <% if message_type == "notice" %>
        <div class="bg-green-500 text-white text-center p-3">
          <%= message %>
        </div>
      <% else %>
        <div class="bg-red-500 text-white text-center p-3">
          <%= message %>
        </div>
      <% end %>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<h1 class="text-center text-3xl font-semibold text-gray-800 mt-8">Organize Your Life</h1>


<div class="container mx-auto px-4">

  <div class="mt-12 text-center mb-8">
    <%= link_to "Register to Create Todos", register_path, class: "bg-blue-500 text-white px-4 py-2 rounded-md" %>
  </div>

  <p class="text-center text-lg font-300 text-gray-800 mt-12">Already have an account?</p>

  <div class="mt-3 text-center mb-8">
    <%= link_to "Login here", login_path, class: "text-blue-600" %>
  </div>

</div>

app/views/shared/_errors.html.erb
<% if active_record_obj.errors.any? %>
  <div class="bg-red-100 border border-red-400 text-red-700 mb-6 px-4 py-3 rounded relative" role="alert">
    <strong class="font-bold">
      <%= pluralize(active_record_obj.errors.size, "error") %>
       prohibited this <%= model %> from being saved:
    </strong>
    <ul class="list-disc list-inside">
      <% active_record_obj.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/todos/_form.html.erb
<%= form_with(model: [@user, @todo], class: "flex flex-col items-center justify-start pt-8") do |f| %>
  
  <%= render partial: "shared/errors", locals: { active_record_obj: todo, model: :todo } %>

  <div class="mb-4 w-full md:w-1/3">
    <%= f.label :title, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= f.text_field :title, autofocus: true, placeholder: "What do you want to do?", class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div>
    <%= f.submit class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer" %>
  </div>

<% end %>

app/views/todos/edit.html.erb
<h1 class="text-center text-3xl font-semibold text-gray-800 mt-8">Edit This Todo</h1>

<%= render "form", todo: @todo %>

app/views/todos/index.html.erb
<div class="container mx-auto px-4">

  <div class="mt-8 text-center mb-8">
    <%= link_to "Add Todo", new_user_todo_path(current_user), class: "bg-blue-500 text-white px-4 py-2 rounded-md" %>
  </div>

  <h3 class="text-2xl mb-5 text-center">You have <%= pluralize(@uncompleted_todos_count, "thing") %> to do today</h3>

  <div class="w-1/2 mx-auto">
    <ul class="pl-5">
      <% @todos.each do |todo| %>
        <li class="mb-2">
          <div class="flex justify-between items-center bg-gray-50 p-2 rounded-md">
            <div class="text-lg text-gray-500 p-2">
              <%= todo.title %>
            </div>
            <div class="flex space-x-2">
              <% if todo.completed? %>
                <span>
                  <%= link_to toggle_completed_user_todo_path(todo.user, todo), data: { turbo_method: :patch } do %>
                    <i class="fas fa-times text-blue-500 mr-4"></i>
                  <% end %>
                </span>
              <% else %>
                <span>
                  <%= link_to toggle_completed_user_todo_path(todo.user, todo), data: { turbo_method: :patch } do %>
                    <i class="fas fa-check text-green-500 mr-4"></i>
                  <% end %>
                </span>
              <% end %>
              <span>
                <%= link_to edit_user_todo_path(todo.user, todo) do %>
                  <i class="fas fa-edit text-yellow-500 mr-4"></i>
                <% end %>
              </span>
              <span>
                <%= link_to user_todo_path(todo.user, todo), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
                  <i class="fas fa-trash text-red-500"></i>
                <% end %>
              </span>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>

</div>

app/views/todos/new.html.erb
<h1 class="text-center text-3xl font-semibold text-gray-800 mt-8">Add New Todo</h1>

<%= render "form", todo: @todo %>

app/views/users/_form.html.erb
<%= form_with(model: user, class: "flex flex-col items-center justify-start pt-8") do |f| %>

  <%= render partial: "shared/errors", locals: { active_record_obj: user, model: :user } %>

  <div class="mb-4 w-full md:w-1/3">
    <%= f.label :username, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= f.text_field :username, autofocus: true, placeholder: "Choose a username (max. 25 chars)", class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4 w-full md:w-1/3">
    <%= f.label :email, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= f.email_field :email, placeholder: "Your primary email address", class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4 w-full md:w-1/3">
    <%= f.label :password, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= f.password_field :password, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4 w-full md:w-1/3">
    <%= f.label :password_confirmation, "Re-type your password", class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= f.password_field :password_confirmation, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div>
    <% submit_text = user.new_record? ? "Register" : "Update Profile" %>
    <%= f.submit submit_text, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 class="text-center text-3xl font-semibold text-gray-800 mt-8">Update Profile</h1>

<%= render partial: "form", locals: { user: @user } %>

app/views/users/new.html.erb
<h1 class="text-center text-3xl font-semibold text-gray-800 mt-8">Register</h1>

<%= render partial: "form", locals: { user: @user } %>

app/views/users/show.html.erb
<div class="mx-auto text-center w-full max-w-xl">
  <h1 class="text-4xl font-bold my-4"><%= @user.username %></h1>

  <p class="text-xl mb-2">
    <%= @user.email %>
  </p>

  <div class="mb-4">
    <%= link_to 'Edit profile', edit_user_path(@user), class: "inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
    <%= link_to "Delete account", user_path(@user), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "inline-block bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded ml-4" %>
  </div>

  <h3 class="text-xl mb-4">Manage My Todo List</h3>

  <div class="mb-4">
    <%= link_to "View My Todos", user_todos_path(@user), class: "inline-block bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded" %>
  </div>

  <div class="mb-4">
    <%= link_to "Add New Todo", new_user_todo_path(@user), class: "inline-block bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded" %>
  </div>

</div>